# Generated by Django 5.2.7 on 2025-10-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
    ]
