# Generated by Django 5.2.5 on 2025-10-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0002_vehicle_is_available"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="fuel_type",
            field=models.CharField(
                choices=[
                    ("Petrol", "Petrol"),
                    ("Diesel", "Diesel"),
                    ("Electric", "Electric"),
                ],
                default="Petrol",
                max_length=20,
            ),
        ),
    ]
